services:
  postgres:
    image: postgres
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
       POSTGRES_DB: postgres
       PGDATA: /data/postgres
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - webapi-network
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: balalzadehhamid79@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8090:80"
    networks:
      - webapi-network
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis
    ports:
      - "6379:6379"
    networks:
      - webapi-network


volumes:
  postgres:
  pgadmin:
  redis:
  logs:

networks:
  webapi-network:
    driver: bridge